# Generated by Django 5.2.1 on 2025-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livechat", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
